import { Reservation } from 'src/reservations/entities/reservation.entity';
import { Entity, Column, PrimaryGeneratedColumn, OneToMany } from 'typeorm';

@Entity()
export class Book {

  /**
  * Autogenerated 
  */
  @PrimaryGeneratedColumn()
  id: number;

  /**
  * Title of the book - 
  */
  @Column({ unique: false })
  title: string;

  @Column()
  genre: string;

  @Column('text')
  description: string;

  @Column()
  author: string;

  @Column()
  publisher: string;

  @Column()
  pages: number;
  /**
  *URL of the image
  *@example https://imagenes.com/foto-gratis/imagendelibro.jpg
  */
  @Column('text')
  image_url: string;

  /**
  * Array of reservations
  */
  @OneToMany(() => Reservation, bookReservation => bookReservation.book)
  bookReservations: Reservation[];
}