import { User } from "src/users/entities/user.entity";
import { Column, Entity, ManyToMany, PrimaryGeneratedColumn } from "typeorm";

@Entity()
export class Role {
    /**
     * Autogenerated.
     */
    @PrimaryGeneratedColumn()
    id: number;

    /**
     * Role must be unique
     * @example ADMIN, USER
     */
    @Column({ unique: true })
    role: String;

    @ManyToMany(() => User, user => user.roles)
    users: User[];
}
