import { Column, Entity, PrimaryGeneratedColumn } from "typeorm";

@Entity()
export class Role {
    /**
     * Autogenerated.
     */
    @PrimaryGeneratedColumn()
    id: number;

    /**
     * Role must be unique
     * @example ADMIN, USER
     */
    @Column({ unique: true })
    role: String;
}
